name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3

      - name: Compile LaTeX document with latexmk
        run: |
          sudo apt-get install -y texlive-xetex
          latexmk -pdf -interaction=nonstopmode -synctex=1 report.tex
        continue-on-error: true  # Позволяет перейти к следующему шагу, даже если этот завершился с ошибкой

      - name: Compile LaTeX document with pdflatex (if needed)
        if: failure()  # Выполняется только если предыдущий шаг завершился с ошибкой
        run: |
          sudo apt-get install -y texlive-latex-base
          pdflatex -interaction=nonstopmode -synctex=1 report.tex

      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: report.pdf
