name: Сборка LaTeX-документа
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Настройка репозитория Git
        uses: actions/checkout@v3

      - name: Установка TeXLive
        run: |
          sudo apt-get install -y texlive-xetex
                  
      - name: Компиляция библиографии с помощью BibTeX
        run: |
          bibtex report
        continue-on-error: false
        
      - name: Компиляция LaTeX-документа с использованием pdflatex
        run: |
          sudo apt-get install -y texlive-latex-base
          pdflatex -interaction=nonstopmode -synctex=1 report.tex
        continue-on-error: false
        
      - name: Загрузка файла PDF
        uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: report.pdf
